motion_module_path: "./models/Motion_Module/mm_sdxl_v10_beta.ckpt"

seed:           -1

guidance_scale: 8.5
steps: 100

prompt:
  - "A panda standing on a surfboard in the ocean in sunset, 4k, high resolution.Realistic, Cinematic, high resolution"
  - "A disoriented astronaut, lost in a galaxy of swirling colors, floating in zero gravity, grasping at memories, poignant loneliness, stunning realism, cosmic chaos, emotional depth, 12K, hyperrealism, unforgettable, mixed media, celestial, dark, introspective"

n_prompt:
  - ""
  - ""